#!/usr/bin/ruby

changelog = false
gem_install = false

ARGF.each_line do |line|
  changelog ||= line =~ /%changelog/
  comment = line =~ /\s*#/

  unless changelog or comment
    # Remove Requires, which are now autogenerated.
    next if line =~ /\bRequires:.*ruby.*/

    # Remove rubygem virtual provide, which is now autogenerated.
    next if line =~ /\bProvides:.*rubygem\(.*\).*/

    # Simplify binary extensions.
    line.gsub!(/(mkdir -p %{buildroot}%{gem_extdir_mri}).*/, '\1')
    line.gsub!(/mv %{buildroot}%{gem_libdir}\/.*\.so.*/, \
      "cp -pa .%{gem_extdir_mri}/* %{buildroot}%{gem_extdir_mri}/")
  end

  puts line
end
