#!/usr/bin/ruby

changelog = false
gem_install = false

ARGF.each_line do |line|
  changelog ||= line =~ /%changelog/
  comment = line =~ /\s*#/

  unless changelog or comment
    # Remove Requires, which are now autogenerated.
    next if line =~ /\bRequires:.*ruby.*/

    # Remove rubygem virtual provide, which is now autogenerated.
    next if line =~ /\bProvides:.*rubygem\(.*\).*/

    # Simplify binary extensions.
    line.gsub!(/(mkdir -p %{buildroot}%{gem_extdir_mri}).*/, '\1')
    line.gsub!(/mv %{buildroot}%{gem_(inst|lib)dir}\/.*\.so.*/, \
      "cp -a .%{gem_extdir_mri}/{gem.build_complete,*.so} %{buildroot}%{gem_extdir_mri}/\n\n" +
      "# Prevent dangling symlink in -debuginfo.\n" +
      "rm -rf %{buildroot}%{gem_instdir}/ext\n")

    # Always remove binary extension dir.
    next if line =~ /%exclude %{gem_instdir}\/ext/
  end

  puts line
end
