#!/usr/bin/ruby

changelog = false
gem_install = false

ARGF.each_line do |line|
  changelog ||= line =~ /%changelog/
  comment = line =~ /\s*#/

  unless changelog or comment
    # Remove Requires, which are now autogenerated.
    next if line =~ /\bRequires:.*ruby.*/

    # Remove rubygem virtual provide, which is now autogenerated.
    next if line =~ /\bProvides:.*rubygem\(.*\).*/
  end

  puts line
end
